# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ed387497b6ba727139b4ca979c657afbd4a57fadb26bf5f9b084b9cd3bebe697376bf1fdcc3786da80ab7d985fd6895e924c1fa9ee284604dfb9b2bbf64861e

test:
  secret_key_base: 7ac77922bcf1b8906f4b8df41e802fe756e377d07b085a859e596be0e000dc3f5a9a8d8a87f26f30ed8f21c1131a8dbff658c8ce9ac4367bc44aa755cb4d9a97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
